server {
    server_name localhost;
    listen 8000;
    index index.html;
    root ./www/;
    client_max_body_size 1024;
    error_pages 404 error_pages/404.html;

    location / {
        methods GET;
        autoindex off;
    }
}
