server {
	listen 127.0.0.1:8080;
	server_name localhost;
	root www;

	location / {
		root www;
		index index.html;
		autoindex on;
		method GET;
	}

	location /upload/ {
		upload_dir upload/files;
		method POST DELETE;
	}

	location /cgi-bin/ {
		root cgi;
		autoindex on;
		cgi_pass .py /usr/bin/python3;
		cgi_pass .sh /bin/bash;
		method GET POST;
	}

	location /secrets/ {
		root secrets/;
	}
}

server {
	listen 197.0.0.2:8080;
	server_name site1.local;
	root www/site1;

	location / {
		root www/site1;
		index index.html;
		autoindex on;
		method GET;
	}
}

server {
	listen 127.0.0.3:8080;
	server_name site2.local;
	root www/site2;
	index index.html;
}

