server {
    server_name localhost;
    listen 8000;
    index index.html;
    root ./www/;
    client_max_body_size 300000;
    error_pages 404 error_pages/404.html;

    location / {
        methods GET POST DELETE;
        autoindex off;
    }

    location /42 {
        autoindex on;
        index 42.html;
        methods GET;
    }

    location /redir {
        return /42;
    }

    location /upload {
        methods GET POST;
        upload_store ./data/upload;
    }

    location /cgi {
        root ./www/cgi/;
        methods GET POST DELETE;
        index script.py;
        upload_store /data/www/upload;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
    }
}
