server {
	server_name localhost;
	listen 8000;
	index index.html;
	root ./www/;
	client_max_body_size 1024m;
	error_page 404 ./error_pages/404.html;

	location / {
		method GET POST DELETE;
		autoindex off;
	}

	location /42 {
		autoindex on;
		index 42.html;
		method GET;
	}

	location /redir {
		return 302 /42;
	}

	location /upload {
		method GET POST;
		upload_dir ./data/upload;
	}

	location /cgi {
		root ./www/cgi/;
		method GET POST DELETE;
		index script.py;
		upload_dir /data/www/upload;
		cgi_pass .py /usr/bin/python3;
		cgi_pass .sh /bin/bash;
	}
}
