server {
    server_name localhost;
    listen 8000;
    index index.html;
    root ./www;
    client_max_body_size 300000;
    error_pages 404 error_pages/404.html;

    location / {
        methods GET POST DELETE;
        autoindex off;
    }
}

server {
    server_name localhost;
    listen 8001;
    index index2.html;
    root ./www/;
    client_max_body_size 300000;
    error_pages 404 error_pages/404.html;

    location / {
        methods GET POST DELETE;
        autoindex off;
    }
}

server {
    server_name localhost;
    listen 8002;
    index index3.html;
    root ./www/;
    client_max_body_size 300000;
    error_pages 404 error_pages/404.html;

    location / {
        methods GET POST DELETE;
        autoindex off;
    }
}
